#!/bin/sh
dir="$(dirname "$0")"
cf="$1"; test -z "$cf" && cf=current_flr.txt
perl "$dir/check_pd.pl" "$@" < "$cf" || exit 1
today="Last updated: $(date '+%d %B %Y' | sed 's/^0*//')"
/usr/bin/sed -i '' "s/Last updated.*\$/$today/" "$cf"
perl "$dir/flr_to_slr.pl" < "$cf" > current_slr.txt || exit 1
